# Generated by Django 6.0.4 on 2026-04-10 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_room_product_roomproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomproduct',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='room.room'),
        ),
    ]
