# Generated by Django 6.0.4 on 2026-04-10 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_is_selected_alter_cart_end_date_and_more'),
        ('room', '0003_alter_roomproduct_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
        migrations.DeleteModel(
            name='Room_cart',
        ),
    ]
