# Generated by Django 6.0.4 on 2026-04-20 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_room_delete_room_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='is_selected',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='room',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='start_date',
        ),
    ]
