# Generated by Django 6.0.4 on 2026-04-20 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-price_per_day']},
        ),
    ]
