# Generated by Django 6.0.4 on 2026-04-20 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booked_items_booking'),
        ('products', '0002_alter_product_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_deposit_money',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_rent_money',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('total_rent', models.FloatField(default=0)),
                ('total_deposit', models.FloatField(default=0)),
                ('razorpay_order_id', models.CharField()),
                ('is_paid', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
